[default]
APP_ID = "172633887971762"
APP_SECRET = "2f703e247eaae27275db5d5f960e3351"
ACCESS_TOKEN = "EAACdAnWRmbIBAFhVvZCiZA9kKbpK2tjZCxJ4JWhMHZCnEU3owGQCV40Rp0ZAipWZAgZAjmGheo6fw7xALHMHyZCmnHfAcMZAyFjfGzZBARZACsTfre3EiKRZC4ShjpxwaUV3gYaKAtwGgZBqpbeviJ7VmZBC5TrGHvJ1jhjyldVDiJHYwtdPEe9oQ9l4aG"
BUSINESS_ID = "584488375483100"
ACCOUNTS_FILENAME = "C:/Users/Vitaly/Projects/facebook-api/accs.txt"
SLEEP_TIME = "3"
BROWSER_LOCATION = "C:/Program Files (x86)/Mozilla Firefox/firefox.exe"
ACCESS_TOKEN_GETTING_FAULTS_LIMIT_NOTIFICATION = "3"
INACTIVE_ACCOUNTS_LIMIT_NOTIFICATION = "3"
FACEBOOK_GRAPH_URL = "https://graph.facebook.com/v9.0"
FACEBOOK_URL = "https://www.facebook.com"
LOGIN_FORM_EMAIL_FIELD = "email"
LOGIN_FORM_PASSWORD_FIELD = "pass"
LOGIN_FORM_SUBMIT_BUTTON = "u_0_d"
CONFIRM_REQUEST_BUTTON = "a._42ft"
CONFIRM_REQUEST_LINK = "._3m_7 > a:nth-child(1)"
HIDE_BROWSER = false
