# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './../QtDesigner/fbUi_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setBaseSize(QtCore.QSize(600, 600))
        MainWindow.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.centralwidget.setObjectName("centralwidget")
        self.tabsWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabsWidget.setGeometry(QtCore.QRect(3, 10, 594, 561))
        self.tabsWidget.setMinimumSize(QtCore.QSize(300, 300))
        self.tabsWidget.setStyleSheet("padding: 20px;\n"
                                      "color: rgb(46, 52, 54);\n"
                                      "font-size:15px;\n"
                                      "font-weight: normal;\n"
                                      "background-color: white;")
        self.tabsWidget.setObjectName("tabsWidget")
        self.generalTab = QtWidgets.QWidget()
        self.generalTab.setStyleSheet("padding:0;\n"
                                      "font-size:15px;\n"
                                      "font-weight: normal;\n"
                                      "color: rgba(54, 52, 52, 223);\n"
                                      "background-color: white;")
        self.generalTab.setObjectName("generalTab")
        self.startScriptButton = QtWidgets.QPushButton(self.generalTab)
        self.startScriptButton.setGeometry(QtCore.QRect(0, 120, 551, 59))
        self.startScriptButton.setStyleSheet("background-color:rgb(10, 151, 82);\n"
                                             "color: white;\n"
                                             "font-size: 16px;\n"
                                             "font-weight: bold;\n"
                                             "border: none;\n"
                                             "border-radius:5px;")
        self.startScriptButton.setObjectName("startScriptButton")
        self.accountsFilenametInput = QtWidgets.QLineEdit(self.generalTab)
        self.accountsFilenametInput.setGeometry(QtCore.QRect(0, 60, 335, 31))
        self.accountsFilenametInput.setStyleSheet("padding-left:5px;\n"
                                                  "padding-right:5px;\n"
                                                  "background-color: rgba(0, 0, 0, 25);")
        self.accountsFilenametInput.setObjectName("accountsFilenametInput")
        self.accountsFilenameLabel = QtWidgets.QLabel(self.generalTab)
        self.accountsFilenameLabel.setGeometry(QtCore.QRect(0, 32, 471, 17))
        self.accountsFilenameLabel.setObjectName("accountsFilenameLabel")
        self.accountsFilenameButton = QtWidgets.QPushButton(self.generalTab)
        self.accountsFilenameButton.setGeometry(QtCore.QRect(350, 60, 201, 31))
        self.accountsFilenameButton.setStyleSheet("background-color: rgb(32, 74, 135);\n"
                                                  "border:none;\n"
                                                  "border-radius:3px;\n"
                                                  "color: white;")
        self.accountsFilenameButton.setObjectName("accountsFilenameButton")
        self.tabsWidget.addTab(self.generalTab, "")
        self.additionalSettingsTab = QtWidgets.QWidget()
        self.additionalSettingsTab.setStyleSheet("padding:0;\n"
                                                 "font-size:15px;\n"
                                                 "font-weight: normal;\n"
                                                 "color: rgba(54, 52, 52, 223);\n"
                                                 "background-color: white;\n"
                                                 "")
        self.additionalSettingsTab.setObjectName("additionalSettingsTab")
        self.settingsTabWidget = QtWidgets.QTabWidget(self.additionalSettingsTab)
        self.settingsTabWidget.setGeometry(QtCore.QRect(0, 0, 541, 491))
        self.settingsTabWidget.setStyleSheet("")
        self.settingsTabWidget.setObjectName("settingsTabWidget")
        self.appAndBMTabPage = QtWidgets.QWidget()
        self.appAndBMTabPage.setObjectName("appAndBMTabPage")
        self.bMAccountIdtInput = QtWidgets.QLineEdit(self.appAndBMTabPage)
        self.bMAccountIdtInput.setGeometry(QtCore.QRect(30, 340, 470, 31))
        self.bMAccountIdtInput.setStyleSheet("padding-left:5px;\n"
                                             "padding-right:5px;\n"
                                             "background-color: rgba(0, 0, 0, 25);")
        self.bMAccountIdtInput.setObjectName("bMAccountIdtInput")
        self.appIdLabel = QtWidgets.QLabel(self.appAndBMTabPage)
        self.appIdLabel.setGeometry(QtCore.QRect(30, 23, 118, 16))
        self.appIdLabel.setObjectName("appIdLabel")
        self.accessTokenLabel = QtWidgets.QLabel(self.appAndBMTabPage)
        self.accessTokenLabel.setGeometry(QtCore.QRect(30, 186, 461, 17))
        self.accessTokenLabel.setObjectName("accessTokenLabel")
        self.appSecretLabel = QtWidgets.QLabel(self.appAndBMTabPage)
        self.appSecretLabel.setGeometry(QtCore.QRect(30, 103, 154, 17))
        self.appSecretLabel.setObjectName("appSecretLabel")
        self.appSecretInput = QtWidgets.QLineEdit(self.appAndBMTabPage)
        self.appSecretInput.setGeometry(QtCore.QRect(30, 125, 470, 31))
        self.appSecretInput.setStyleSheet("padding-left:5px;\n"
                                          "padding-right:5px;\n"
                                          "background-color: rgba(0, 0, 0, 25);")
        self.appSecretInput.setObjectName("appSecretInput")
        self.bMAccountIdLabel = QtWidgets.QLabel(self.appAndBMTabPage)
        self.bMAccountIdLabel.setGeometry(QtCore.QRect(30, 318, 287, 17))
        self.bMAccountIdLabel.setObjectName("bMAccountIdLabel")
        self.appIdInput = QtWidgets.QLineEdit(self.appAndBMTabPage)
        self.appIdInput.setGeometry(QtCore.QRect(30, 45, 470, 31))
        self.appIdInput.setStyleSheet("padding-left:5px;\n"
                                      "padding-right:5px;\n"
                                      "background-color: rgba(0, 0, 0, 25);")
        self.appIdInput.setObjectName("appIdInput")
        self.accessTokenInput = QtWidgets.QPlainTextEdit(self.appAndBMTabPage)
        self.accessTokenInput.setGeometry(QtCore.QRect(30, 210, 470, 81))
        self.accessTokenInput.setStyleSheet("padding-left:5px;\n"
                                            "padding-right:5px;\n"
                                            "background-color: rgba(0, 0, 0, 25);")
        self.accessTokenInput.setObjectName("accessTokenInput")
        self.settingsTabWidget.addTab(self.appAndBMTabPage, "")
        self.browserTabPage = QtWidgets.QWidget()
        self.browserTabPage.setObjectName("browserTabPage")
        self.browserLocationLabel = QtWidgets.QLabel(self.browserTabPage)
        self.browserLocationLabel.setGeometry(QtCore.QRect(30, 28, 172, 17))
        self.browserLocationLabel.setObjectName("browserLocationLabel")
        self.browserLocationInput = QtWidgets.QLineEdit(self.browserTabPage)
        self.browserLocationInput.setGeometry(QtCore.QRect(30, 50, 321, 31))
        self.browserLocationInput.setStyleSheet("padding-left:5px;\n"
                                                "padding-right:5px;\n"
                                                "background-color: rgba(0, 0, 0, 25);")
        self.browserLocationInput.setObjectName("browserLocationInput")
        self.hideBrowserCheckBox = QtWidgets.QCheckBox(self.browserTabPage)
        self.hideBrowserCheckBox.setGeometry(QtCore.QRect(30, 120, 428, 18))
        self.hideBrowserCheckBox.setObjectName("hideBrowserCheckBox")
        self.browserLocationButton = QtWidgets.QPushButton(self.browserTabPage)
        self.browserLocationButton.setGeometry(QtCore.QRect(360, 50, 151, 31))
        self.browserLocationButton.setStyleSheet("background-color: rgb(32, 74, 135);\n"
                                                 "border:none;\n"
                                                 "border-radius:3px;\n"
                                                 "color: white;")
        self.browserLocationButton.setObjectName("browserLocationButton")
        self.settingsTabWidget.addTab(self.browserTabPage, "")
        self.scriptTabPage = QtWidgets.QWidget()
        self.scriptTabPage.setObjectName("scriptTabPage")
        self.sleepTimeLabel = QtWidgets.QLabel(self.scriptTabPage)
        self.sleepTimeLabel.setGeometry(QtCore.QRect(30, 33, 411, 17))
        self.sleepTimeLabel.setObjectName("sleepTimeLabel")
        self.sleepTimeIdInput = QtWidgets.QLineEdit(self.scriptTabPage)
        self.sleepTimeIdInput.setGeometry(QtCore.QRect(30, 60, 470, 31))
        self.sleepTimeIdInput.setStyleSheet("padding-left:5px;\n"
                                            "padding-right:5px;\n"
                                            "background-color: rgba(0, 0, 0, 25);")
        self.sleepTimeIdInput.setObjectName("sleepTimeIdInput")
        self.accessTokenFaultsLimitInput = QtWidgets.QLineEdit(self.scriptTabPage)
        self.accessTokenFaultsLimitInput.setGeometry(QtCore.QRect(30, 140, 470, 31))
        self.accessTokenFaultsLimitInput.setStyleSheet("padding-left:5px;\n"
                                                       "padding-right:5px;\n"
                                                       "background-color: rgba(0, 0, 0, 25);")
        self.accessTokenFaultsLimitInput.setObjectName("accessTokenFaultsLimitInput")
        self.accessTokenFaultsLimitLabel = QtWidgets.QLabel(self.scriptTabPage)
        self.accessTokenFaultsLimitLabel.setGeometry(QtCore.QRect(30, 113, 459, 17))
        self.accessTokenFaultsLimitLabel.setObjectName("accessTokenFaultsLimitLabel")
        self.inactiveAccountsLimitNotificationInput = QtWidgets.QLineEdit(self.scriptTabPage)
        self.inactiveAccountsLimitNotificationInput.setGeometry(QtCore.QRect(30, 220, 470, 31))
        self.inactiveAccountsLimitNotificationInput.setStyleSheet("padding-left:5px;\n"
                                                                  "padding-right:5px;\n"
                                                                  "background-color: rgba(0, 0, 0, 25);")
        self.inactiveAccountsLimitNotificationInput.setObjectName("inactiveAccountsLimitNotificationInput")
        self.inactiveAccountsLimitNotificationLabel = QtWidgets.QLabel(self.scriptTabPage)
        self.inactiveAccountsLimitNotificationLabel.setGeometry(QtCore.QRect(30, 194, 458, 17))
        self.inactiveAccountsLimitNotificationLabel.setObjectName("inactiveAccountsLimitNotificationLabel")
        self.facebookGraphUrlInput = QtWidgets.QLineEdit(self.scriptTabPage)
        self.facebookGraphUrlInput.setGeometry(QtCore.QRect(30, 300, 470, 31))
        self.facebookGraphUrlInput.setStyleSheet("padding-left:5px;\n"
                                                 "padding-right:5px;\n"
                                                 "background-color: rgba(0, 0, 0, 25);")
        self.facebookGraphUrlInput.setObjectName("facebookGraphUrlInput")
        self.facebookGraphUrlLabel = QtWidgets.QLabel(self.scriptTabPage)
        self.facebookGraphUrlLabel.setGeometry(QtCore.QRect(30, 273, 458, 17))
        self.facebookGraphUrlLabel.setObjectName("facebookGraphUrlLabel")
        self.facebookUrlInput = QtWidgets.QLineEdit(self.scriptTabPage)
        self.facebookUrlInput.setGeometry(QtCore.QRect(30, 385, 470, 31))
        self.facebookUrlInput.setStyleSheet("padding-left:5px;\n"
                                            "padding-right:5px;\n"
                                            "background-color: rgba(0, 0, 0, 25);")
        self.facebookUrlInput.setObjectName("facebookUrlInput")
        self.facebookUrlLabel = QtWidgets.QLabel(self.scriptTabPage)
        self.facebookUrlLabel.setGeometry(QtCore.QRect(30, 358, 458, 17))
        self.facebookUrlLabel.setObjectName("facebookUrlLabel")
        self.settingsTabWidget.addTab(self.scriptTabPage, "")
        self.cssSelectorsDescriptionTabPage = QtWidgets.QWidget()
        self.cssSelectorsDescriptionTabPage.setObjectName("cssSelectorsDescriptionTabPage")
        self.loginFormEmailFieldLabel = QtWidgets.QLabel(self.cssSelectorsDescriptionTabPage)
        self.loginFormEmailFieldLabel.setGeometry(QtCore.QRect(30, 63, 458, 17))
        self.loginFormEmailFieldLabel.setObjectName("loginFormEmailFieldLabel")
        self.loginFormEmailFieldInput = QtWidgets.QLineEdit(self.cssSelectorsDescriptionTabPage)
        self.loginFormEmailFieldInput.setGeometry(QtCore.QRect(30, 90, 470, 31))
        self.loginFormEmailFieldInput.setStyleSheet("padding-left:5px;\n"
                                                    "padding-right:5px;\n"
                                                    "background-color: rgba(0, 0, 0, 25);")
        self.loginFormEmailFieldInput.setObjectName("loginFormEmailFieldInput")
        self.cssSelectorsDescriptionLabel = QtWidgets.QLabel(self.cssSelectorsDescriptionTabPage)
        self.cssSelectorsDescriptionLabel.setGeometry(QtCore.QRect(30, 20, 470, 17))
        self.cssSelectorsDescriptionLabel.setObjectName("cssSelectorsDescriptionLabel")
        self.loginFormPasswordFieldLabel = QtWidgets.QLabel(self.cssSelectorsDescriptionTabPage)
        self.loginFormPasswordFieldLabel.setGeometry(QtCore.QRect(30, 140, 458, 17))
        self.loginFormPasswordFieldLabel.setObjectName("loginFormPasswordFieldLabel")
        self.loginFormPasswordFieldInput = QtWidgets.QLineEdit(self.cssSelectorsDescriptionTabPage)
        self.loginFormPasswordFieldInput.setGeometry(QtCore.QRect(30, 167, 470, 31))
        self.loginFormPasswordFieldInput.setStyleSheet("padding-left:5px;\n"
                                                       "padding-right:5px;\n"
                                                       "background-color: rgba(0, 0, 0, 25);")
        self.loginFormPasswordFieldInput.setObjectName("loginFormPasswordFieldInput")
        self.loginFormSubmitButtonInput = QtWidgets.QLineEdit(self.cssSelectorsDescriptionTabPage)
        self.loginFormSubmitButtonInput.setGeometry(QtCore.QRect(30, 248, 470, 31))
        self.loginFormSubmitButtonInput.setStyleSheet("padding-left:5px;\n"
                                                      "padding-right:5px;\n"
                                                      "background-color: rgba(0, 0, 0, 25);")
        self.loginFormSubmitButtonInput.setObjectName("loginFormSubmitButtonInput")
        self.loginFormSubmitButtonLabel = QtWidgets.QLabel(self.cssSelectorsDescriptionTabPage)
        self.loginFormSubmitButtonLabel.setGeometry(QtCore.QRect(30, 221, 458, 17))
        self.loginFormSubmitButtonLabel.setObjectName("loginFormSubmitButtonLabel")
        self.confirmRequestButtonInput = QtWidgets.QLineEdit(self.cssSelectorsDescriptionTabPage)
        self.confirmRequestButtonInput.setGeometry(QtCore.QRect(30, 323, 470, 31))
        self.confirmRequestButtonInput.setStyleSheet("padding-left:5px;\n"
                                                     "padding-right:5px;\n"
                                                     "background-color: rgba(0, 0, 0, 25);")
        self.confirmRequestButtonInput.setObjectName("confirmRequestButtonInput")
        self.confirmRequestButtonLabel = QtWidgets.QLabel(self.cssSelectorsDescriptionTabPage)
        self.confirmRequestButtonLabel.setGeometry(QtCore.QRect(30, 300, 458, 17))
        self.confirmRequestButtonLabel.setObjectName("confirmRequestButtonLabel")
        self.confirmRequestLinkInput = QtWidgets.QLineEdit(self.cssSelectorsDescriptionTabPage)
        self.confirmRequestLinkInput.setGeometry(QtCore.QRect(30, 400, 470, 31))
        self.confirmRequestLinkInput.setStyleSheet("padding-left:5px;\n"
                                                   "padding-right:5px;\n"
                                                   "background-color: rgba(0, 0, 0, 25);")
        self.confirmRequestLinkInput.setObjectName("confirmRequestLinkInput")
        self.confirmRequestLinkLabel = QtWidgets.QLabel(self.cssSelectorsDescriptionTabPage)
        self.confirmRequestLinkLabel.setGeometry(QtCore.QRect(30, 373, 474, 17))
        self.confirmRequestLinkLabel.setObjectName("confirmRequestLinkLabel")
        self.settingsTabWidget.addTab(self.cssSelectorsDescriptionTabPage, "")
        self.tabsWidget.addTab(self.additionalSettingsTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabsWidget.setCurrentIndex(0)
        self.settingsTabWidget.setCurrentIndex(0)
        MainWindow.destroyed.connect(self.statusbar.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Facebook API Script"))
        self.startScriptButton.setToolTip(
            _translate("MainWindow", "Проверьте правильность настроек скрита и нажмите кнопку Старт"))
        self.startScriptButton.setText(_translate("MainWindow", "Старт"))
        self.accountsFilenametInput.setText(_translate("MainWindow", "accs.txt"))
        self.accountsFilenameLabel.setText(
            _translate("MainWindow", "Укажите путь к файлу с исходными данными аккаунтов Клиентов:"))
        self.accountsFilenameButton.setText(_translate("MainWindow", "Найти файл"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.generalTab), _translate("MainWindow", "Главная"))
        self.bMAccountIdtInput.setText(_translate("MainWindow", "584488375483100"))
        self.appIdLabel.setText(_translate("MainWindow", "Укажите App ID:"))
        self.accessTokenLabel.setToolTip(_translate("MainWindow", "Укажите долгосрочный продленный access tocken"))
        self.accessTokenLabel.setText(_translate("MainWindow", "Укажите Developer Access Token :"))
        self.appSecretLabel.setText(_translate("MainWindow", "Укажите App Secret:"))
        self.appSecretInput.setText(_translate("MainWindow", "2f703e247eaae27275db5d5f960e3351"))
        self.bMAccountIdLabel.setText(_translate("MainWindow", "Укажите ID аккаунта бизнес менеджера:"))
        self.appIdInput.setText(_translate("MainWindow", "172633887971762"))
        self.accessTokenInput.setPlainText(_translate("MainWindow",
                                                      "EAACdAnWRmbIBAFhVvZCiZA9kKbpK2tjZCxJ4JWhMHZCnEU3owGQCV40Rp0ZAipWZAgZAjmGheo6fw7xALHMHyZCmnHfAcMZAyFjfGzZBARZACsTfre3EiKRZC4ShjpxwaUV3gYaKAtwGgZBqpbeviJ7VmZBC5TrGHvJ1jhjyldVDiJHYwtdPEe9oQ9l4aG"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.appAndBMTabPage),
                                          _translate("MainWindow", "FB App и BM аккаунт"))
        self.browserLocationLabel.setText(_translate("MainWindow", "Путь до файла браузера"))
        self.browserLocationInput.setToolTip(_translate("MainWindow",
                                                        "Для Windows: \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\' или \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'. Для Linux: \'/usr/bin/firefox\' "))
        self.browserLocationInput.setText(_translate("MainWindow", "C:\\Program Files\\Mozilla Firefox\\firefox.exe"))
        self.hideBrowserCheckBox.setText(_translate("MainWindow", "Скрыть окно браузера во время выполнения программы"))
        self.browserLocationButton.setText(_translate("MainWindow", "Найти файл"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.browserTabPage),
                                          _translate("MainWindow", "Браузер"))
        self.sleepTimeLabel.setText(_translate("MainWindow", "Время ожидания загрузки страниц браузером в секундах:"))
        self.sleepTimeIdInput.setToolTip(_translate("MainWindow",
                                                    "Для Windows: \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\' или \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'. Для Linux: \'/usr/bin/firefox\' "))
        self.sleepTimeIdInput.setText(_translate("MainWindow", "3"))
        self.accessTokenFaultsLimitInput.setToolTip(_translate("MainWindow",
                                                               "Для Windows: \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\' или \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'. Для Linux: \'/usr/bin/firefox\' "))
        self.accessTokenFaultsLimitInput.setText(_translate("MainWindow", "3"))
        self.accessTokenFaultsLimitLabel.setText(
            _translate("MainWindow", "Максимальное кол-во попыток получить access_token клиентов:"))
        self.inactiveAccountsLimitNotificationInput.setToolTip(_translate("MainWindow",
                                                                          "Для Windows: \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\' или \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'. Для Linux: \'/usr/bin/firefox\' "))
        self.inactiveAccountsLimitNotificationInput.setText(_translate("MainWindow", "3"))
        self.inactiveAccountsLimitNotificationLabel.setText(
            _translate("MainWindow", "Максимальное коли-во найденных неактивных рекл. аккаунтов:"))
        self.facebookGraphUrlInput.setToolTip(_translate("MainWindow",
                                                         "Для Windows: \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\' или \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'. Для Linux: \'/usr/bin/firefox\' "))
        self.facebookGraphUrlInput.setText(_translate("MainWindow", "https://graph.facebook.com/v9.0"))
        self.facebookGraphUrlLabel.setText(_translate("MainWindow", "Версия Facebook Graph API:"))
        self.facebookUrlInput.setToolTip(_translate("MainWindow",
                                                    "Для Windows: \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\' или \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'. Для Linux: \'/usr/bin/firefox\' "))
        self.facebookUrlInput.setText(_translate("MainWindow", "https://www.facebook.com"))
        self.facebookUrlLabel.setText(_translate("MainWindow", "Ссылка на фейсбук:"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.scriptTabPage),
                                          _translate("MainWindow", "Программа"))
        self.loginFormEmailFieldLabel.setText(_translate("MainWindow", "Форма авторизации поле email"))
        self.loginFormEmailFieldInput.setToolTip(_translate("MainWindow",
                                                            "Для Windows: \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\' или \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'. Для Linux: \'/usr/bin/firefox\' "))
        self.loginFormEmailFieldInput.setText(_translate("MainWindow", "email"))
        self.cssSelectorsDescriptionLabel.setText(
            _translate("MainWindow", "CSS селекторы  (Поменять, если перестали находиться элементы)"))
        self.loginFormPasswordFieldLabel.setText(_translate("MainWindow", "Форма авторизации поле пароль"))
        self.loginFormPasswordFieldInput.setToolTip(_translate("MainWindow",
                                                               "Для Windows: \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\' или \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'. Для Linux: \'/usr/bin/firefox\' "))
        self.loginFormPasswordFieldInput.setText(_translate("MainWindow", "pass"))
        self.loginFormSubmitButtonInput.setToolTip(_translate("MainWindow",
                                                              "Для Windows: \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\' или \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'. Для Linux: \'/usr/bin/firefox\' "))
        self.loginFormSubmitButtonInput.setText(_translate("MainWindow", "u_0_d"))
        self.loginFormSubmitButtonLabel.setText(
            _translate("MainWindow", "Форма авторизации кнопка для отправки логина и пароля:"))
        self.confirmRequestButtonInput.setToolTip(_translate("MainWindow",
                                                             "Для Windows: \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\' или \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'. Для Linux: \'/usr/bin/firefox\' "))
        self.confirmRequestButtonInput.setText(_translate("MainWindow", "a._42ft"))
        self.confirmRequestButtonLabel.setText(_translate("MainWindow", "Рекламный аккаунт кнопка Ответить на запрос:"))
        self.confirmRequestLinkInput.setToolTip(_translate("MainWindow",
                                                           "Для Windows: \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\' или \'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'. Для Linux: \'/usr/bin/firefox\' "))
        self.confirmRequestLinkInput.setText(_translate("MainWindow", "._3m_7 > a:nth-child(1)"))
        self.confirmRequestLinkLabel.setText(
            _translate("MainWindow", "Рекламный аккаунт модальное окно ссылка Предоставить доступ:"))
        self.settingsTabWidget.setTabText(self.settingsTabWidget.indexOf(self.cssSelectorsDescriptionTabPage),
                                          _translate("MainWindow", "CSS селекторы"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.additionalSettingsTab),
                                   _translate("MainWindow", "Настройки"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
